#include <QProcess>
#include <QMessageBox>
#include <QHeaderView>
#include <QApplication>
#include <QGuiApplication>
#include <QScreen>
#include <QClipboard>
#include <QDir>
#include <QStandardPaths>
#include <QDateTime>
#include <QFileInfo>
#include <QProcessEnvironment>
#include <QFile>
#include <QFileDialog>
#include <QInputDialog>
#include <QMessageBox>
#include <QRegularExpression>
#include <QApplication>
#include <QSettings>
#include <QTimer>
#include <QDebug>
#include <QFileSystemModel>
#include <QTextStream>
#include <QNetworkAccessManager>
#include <QNetworkReply>
#include <QNetworkRequest>
#include <QDesktopServices>
#include <unistd.h>